// Global, simple, no imports, no modules, hard to break.
window.RUNES = [
  { n: 1, name: "Fehu", glyph: "ᚠ", emoji: "🐄", meaning: "Wealth, resources" },
  { n: 2, name: "Uruz", glyph: "ᚢ", emoji: "🐃", meaning: "Strength, vitality" },
  { n: 3, name: "Thurisaz", glyph: "ᚦ", emoji: "🛡️", meaning: "Boundary, defense" },
  { n: 4, name: "Ansuz", glyph: "ᚨ", emoji: "📡", meaning: "Signal, speech" },
  { n: 5, name: "Raidho", glyph: "ᚱ", emoji: "🏇", meaning: "Journey, right action" },
  { n: 6, name: "Kenaz", glyph: "ᚲ", emoji: "🔦", meaning: "Torch, insight" },
  { n: 7, name: "Gebo", glyph: "ᚷ", emoji: "🎁", meaning: "Gift, exchange" },
  { n: 8, name: "Wunjo", glyph: "ᚹ", emoji: "🎵", meaning: "Joy, harmony" },
  { n: 9, name: "Hagalaz", glyph: "ᚺ", emoji: "⛈️", meaning: "Disruption, reset" },
  { n: 10, name: "Nauthiz", glyph: "ᚾ", emoji: "⚖️", meaning: "Need, constraint" },
  { n: 11, name: "Isa", glyph: "ᛁ", emoji: "🧊", meaning: "Stillness, pause" },
  { n: 12, name: "Jera", glyph: "ᛃ", emoji: "📅", meaning: "Cycle, harvest" },
  { n: 13, name: "Eihwaz", glyph: "ᛇ", emoji: "🏹", meaning: "Endurance, transition" },
  { n: 14, name: "Perthro", glyph: "ᛈ", emoji: "🎲", meaning: "Mystery, chance" },
  { n: 15, name: "Algiz", glyph: "ᛉ", emoji: "🦌", meaning: "Protection, alertness" },
  { n: 16, name: "Sowilo", glyph: "ᛊ", emoji: "☀️", meaning: "Clarity, success" },
  { n: 17, name: "Tiwaz", glyph: "ᛏ", emoji: "⚔️", meaning: "Justice, sacrifice" },
  { n: 18, name: "Berkano", glyph: "ᛒ", emoji: "🤱", meaning: "Nurture, growth" },
  { n: 19, name: "Ehwaz", glyph: "ᛖ", emoji: "🛶", meaning: "Partnership, movement" },
  { n: 20, name: "Mannaz", glyph: "ᛗ", emoji: "🧩", meaning: "Humanity, self" },
  { n: 21, name: "Laguz", glyph: "ᛚ", emoji: "🌊", meaning: "Flow, intuition" },
  { n: 22, name: "Ingwaz", glyph: "ᛜ", emoji: "🌱", meaning: "Seed, potential" },
  { n: 23, name: "Dagaz", glyph: "ᛞ", emoji: "👁️", meaning: "Breakthrough, dawn" },
  { n: 24, name: "Othala", glyph: "ᛟ", emoji: "🏠", meaning: "Home, inheritance" }
];
