export const RUNES = [
  { n: 1, name: "Fehu", glyph: "ᚠ", sound: "f", hint: "wealth, cattle" },
  { n: 2, name: "Uruz", glyph: "ᚢ", sound: "u", hint: "strength, aurochs" },
  { n: 3, name: "Thurisaz", glyph: "ᚦ", sound: "th", hint: "thorn, giant" },
  { n: 4, name: "Ansuz", glyph: "ᚨ", sound: "a", hint: "mouth, message" },
  { n: 5, name: "Raidho", glyph: "ᚱ", sound: "r", hint: "ride, road" },
  { n: 6, name: "Kenaz", glyph: "ᚲ", sound: "k", hint: "torch, knowledge" },
  { n: 7, name: "Gebo", glyph: "ᚷ", sound: "g", hint: "gift, exchange" },
  { n: 8, name: "Wunjo", glyph: "ᚹ", sound: "w", hint: "joy, harmony" },

  { n: 9, name: "Hagalaz", glyph: "ᚺ", sound: "h", hint: "hail, disruption" },
  { n: 10, name: "Nauthiz", glyph: "ᚾ", sound: "n", hint: "need, constraint" },
  { n: 11, name: "Isa", glyph: "ᛁ", sound: "i", hint: "ice, stillness" },
  { n: 12, name: "Jera", glyph: "ᛃ", sound: "j", hint: "year, harvest" },
  { n: 13, name: "Eiwaz", glyph: "ᛇ", sound: "ei", hint: "yew, endurance" },
  { n: 14, name: "Perthro", glyph: "ᛈ", sound: "p", hint: "chance, hidden" },
  { n: 15, name: "Algiz", glyph: "ᛉ", sound: "z", hint: "elk, protection" },
  { n: 16, name: "Sowilo", glyph: "ᛊ", sound: "s", hint: "sun, success" },

  { n: 17, name: "Tiwaz", glyph: "ᛏ", sound: "t", hint: "Týr, sacrifice" },
  { n: 18, name: "Berkano", glyph: "ᛒ", sound: "b", hint: "birch, growth" },
  { n: 19, name: "Ehwaz", glyph: "ᛖ", sound: "e", hint: "horse, teamwork" },
  { n: 20, name: "Mannaz", glyph: "ᛗ", sound: "m", hint: "humanity, self" },
  { n: 21, name: "Laguz", glyph: "ᛚ", sound: "l", hint: "water, flow" },
  { n: 22, name: "Ingwaz", glyph: "ᛜ", sound: "ng", hint: "seed, inner life" },
  { n: 23, name: "Dagaz", glyph: "ᛞ", sound: "d", hint: "daybreak, shift" },
  { n: 24, name: "Othala", glyph: "ᛟ", sound: "o", hint: "estate, heritage" },
];
